Bio autosign
obi-wallet/obi-wallet pull request #164
Opened 2022-09-24 16:03 UTC by HERRKIN

2022-09-24 18:52 UTC, inyono requested changes

2022-09-24 18:52 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/signature-modal/index.tsx
> +            }, 1000);
That should be cleaned up.

2022-09-24 18:52 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/signature-modal/index.tsx
> +            clearTimeout(time);
same

2022-09-24 18:52 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/signature-modal/index.tsx
> +              Preparing..
```suggestion
              Preparing…
```

2022-09-24 18:52 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/onboarding/create-multisig/3-biometrics/index.tsx
> +    const scanBiometrics = async () => {
Please move that function before the `useEffect` that uses it.

2022-09-24 18:52 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/onboarding/create-multisig/3-biometrics/index.tsx
> +              navigation.navigate("create-multisig-phone-number");
Here we need a state that tracks whether `scanBiometrics` has been executed successfully. Because if not, `scanBiometrics` has to be executed again on button click.

2022-09-24 21:15 UTC, HERRKIN commented on obi-wallet/apps/mobile/src/app/screens/components/signature-modal/index.tsx
> +            clearTimeout(time);
thanks I thought I had.

2022-09-27 15:16 UTC, inyono approved these changes

2022-09-27 15:16 UTC, merged