Add Splash Screen iOS+Android
obi-wallet/obi-wallet pull request #201
Opened 2022-10-22 06:14 UTC by BlockJayn

Added Splash-Screen on App-Load (prevents the screen from showing just a "white screen" till everything is loaded)

https://user-images.githubusercontent.com/99530800/197323392-54651506-2229-456b-81c3-706c3e538ddf.mov

2022-10-24 17:49 UTC, inyono requested changes

2022-10-24 17:49 UTC, inyono commented on obi-wallet/apps/mobile/src/app/splash-screen/index.tsx
> +const HIDDEN = "Hidden";
That should be an [Enum](https://www.typescriptlang.org/docs/handbook/enums.html).

2022-10-24 17:49 UTC, inyono commented on obi-wallet/apps/mobile/src/app/splash-screen/index.tsx
> +export function WithSplashScreen({
Instead of showing & animating the loop logo (and therefore having a minimum time where the splash screen is visible), please show a screen that is similar to the possible initial screens (i.e. welcome or home) and move to the initial screen ASAP. See [Launching - Patterns - Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/patterns/launching).

Most likely, changing `rootView.backgroundColor` is already enough.

2022-10-26 08:43 UTC, BlockJayn commented on obi-wallet/apps/mobile/src/app/splash-screen/index.tsx
> +export function WithSplashScreen({
okay, didn't know that. As suggested I just changed the rootView.backgroundColor (and deleted the Splash-Screen component again)

2022-10-26 21:12 UTC, inyono approved these changes

2022-10-26 21:12 UTC, merged