Feature/social key
obi-wallet/obi-wallet pull request #81
Opened 2022-09-06 21:11 UTC by HERRKIN

2022-09-06 21:33 UTC, inyono requested changes

2022-09-06 21:33 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/keys/social-key/index.tsx
> +>;
- The name `Onboarding3Props` doesn't make sense in that context.
- Why is this in `screens/components` when it is using the onboarding StackParamList, i.e. intended to be used only in the onboarding process?

2022-09-06 21:33 UTC, inyono commented on obi-wallet/libs/common/src/stores/multisig/serialized-data.ts
> +  socialKey: nullable(SerializedSocialKeyPayload),
This needs a migration otherwise existing keys won't be loadable anymore. See `SerializedProxyAddressAnyVersion` as an example on how to handle that.

2022-09-07 19:45 UTC, HERRKIN commented on obi-wallet/apps/mobile/src/app/screens/components/keys/social-key/index.tsx
> +>;
Remember I talked to you about moving some components that may be shared? I know I didn't do it correctly but this was me trying to move a component out of the onboarding and refferencing it there.

2022-09-07 22:46 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/keys/social-key/index.tsx
> +  const { multisigStore } = useStore();
your component should be wrapped in `observer` if you use `useStore`.

2022-09-07 22:59 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/keys/social-key/index.tsx
> +>;
I know. In this case it doesn't make sense though:
- You aren't using `SocialKey` anywhere else yet so no need to move it somewhere else yet.
- The `SocialKey` component is highly dependent on the used context in onboarding since the props use `StackParamList` (onboarding-specific) and the implementation uses `navigation.navigate("onboarding6")` (also onboarding-specific).

So I'll move it into onboarding for now. When you want to use it somewhere else, you can identify how you remove the onboarding-specific stuff from the implementation (e.g. by passing props).

2022-09-07 23:28 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/keys/social-key/index.tsx
> +              keyboardType="number-pad"
Doesn't make sense for this input.

2022-09-07 23:36 UTC, inyono approved these changes

2022-09-07 23:36 UTC, merged

2022-09-08 01:15 UTC, HERRKIN commented on obi-wallet/libs/common/src/stores/multisig/serialized-data.ts
> +  socialKey: nullable(SerializedSocialKeyPayload),
this one I dont understand.

2022-09-08 01:18 UTC, HERRKIN commented on obi-wallet/apps/mobile/src/app/screens/components/keys/social-key/index.tsx
> +              keyboardType="number-pad"
good eye! copy paste catch.

2022-09-08 11:05 UTC, inyono commented on obi-wallet/libs/common/src/stores/multisig/serialized-data.ts
> +  socialKey: nullable(SerializedSocialKeyPayload),
You introduced a breaking change in `SerializedData` by adding `socialKey`. So all existing serialized data (e.g. mine on my iPhone) won't be loadable anymore > I'm losing my current multisig wallet. Therefore, you have to add a migration that tells the app how to migrate the "old" serialized data from the previous app version to the current one including the `socialKey`. While this isn't as important right now (we don't have "real" users yet) it is still an annoyance for devs. And as soon as we have real users, we need migrations anyway.