Fix/assets screen + menu
obi-wallet/obi-wallet pull request #83
Opened 2022-09-06 23:00 UTC by BlockJayn

Fixed assets.tsx + Navigator-Menu
- in accordance to current figma-screen
- added screenWidth/Height component
- modified 
- tested with smallest & biggest screen size
- "placeholder-icon" for Crypto-currencies will be removed later

Old Version:
<img width="600" alt="old-assets" src="https://user-images.githubusercontent.com/99530800/188753648-13d84d1c-31f0-4e62-9545-4d48a757baba.png">

New Version:
<img width="600" alt="new-assets" src="https://user-images.githubusercontent.com/99530800/188753722-4a9473ae-0b02-4e1b-94e5-9e4331260835.png">

2022-09-07 21:42 UTC, inyono requested changes

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/bottom-sheet copy/index.tsx
> +import OriginalBottomSheet, { BottomSheetView } from "@gorhom/bottom-sheet/src";
Why do we have that copy file?

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/screen-size/index.tsx
> +export const smallDeviceMaxHeight = 667;
Usually, constants like that are with caps only (to indicate that they are "global" constants).

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/screen-size/index.tsx
> +export const { width: screenWidth, height: screenHeight } =
That might not work when one rotates the device, right? Might be better to have a function that calculates that if necessary (e.g. `getScreenDimensions`). If we fix portrait mode, it's fine hopefully..,

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/components/assets.tsx
> +                  ? currentNetwork.substring(0, 12) + "..."
Should be "…" instead of "..."

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/components/assets.tsx
> +                ? currentNetwork.substring(0, 13) + "..."
Same

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/components/assets.tsx
> +                ? walletName.substring(0, 12) + "..."
Same

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/components/assets.tsx
> +              ? walletName.substring(0, 15) + "..."
Same

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/components/assets.tsx
> +                ? label.substring(0, 22) + "..."
Same

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/components/assets.tsx
> +              ? label.substring(0, 27) + "..."
Same

2022-09-07 21:42 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/home/index.tsx
> +          paddingTop: screenWidth <= smallDeviceMaxWidth ? 10 : 15,
On second thought: maybe a function `isSmallScreen()` is better. Less duplicated code and also fixes the rotation issue.

2022-09-07 21:44 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/screen-size/index.tsx
> +export const smallDeviceMaxHeight = 667;
See last comment for a better approach

2022-09-07 21:44 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/screen-size/index.tsx
> +export const { width: screenWidth, height: screenHeight } =
See last comment for a better approach

2022-09-08 06:22 UTC, BlockJayn commented on obi-wallet/apps/mobile/src/app/screens/components/bottom-sheet copy/index.tsx
> +import OriginalBottomSheet, { BottomSheetView } from "@gorhom/bottom-sheet/src";
yeah, makes no sense, must have been misclicked somewhere

2022-09-08 08:12 UTC, BlockJayn commented
@inyono Tried to follow your approach (thx 4 that input - awesome!)

Implemented 3 functions now:

- getScreenDimensions()
... for getting current screen-width/height, as well as max values for small devices

- isSmallScreenNumber(smallScreenValue, defaultScreenValue)
... eg.: isSmallScreenNumber(5,10)
... for setting small-device and standard-device number-values anywhere

- isSmallScreenSubstr(string, substr_placeholder, stringcutvalue_smallScreen, stringcutvalue_defaultScreen)
... isSmallScreenSubstr('ThisStringGetsCutOff', '...', 10, 14)
... to cut strings at different positions regarding small- or standard-size devices

2022-09-08 11:09 UTC, inyono approved these changes
Thanks :)

2022-09-08 11:09 UTC, merged