Add Terms&Privacy+replace avatar+name on settings
obi-wallet/obi-wallet pull request #86
Opened 2022-09-07 16:27 UTC by BlockJayn

Add/settings-screen
- Added Terms and Conditions to bottom of screen
- Replaced Avatar with obi-logo
- Replaced Name with "Obi ..."
- Hide Subtext of name

![Simulator Screen Shot - iPhone 13 Pro Max - 2022-09-07 at 17 53 44](https://user-images.githubusercontent.com/99530800/188930416-f866f2e8-df62-429e-bf0b-9e9a44608391.png)

2022-09-07 21:31 UTC, inyono requested changes

2022-09-07 21:31 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/account/index.tsx
> +                //backgroundColor: "red",
Unused code I suppose.

2022-09-07 21:31 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/account/index.tsx
> +                    fontFamily: "Inter",
Inter is already the default font family used by our `Text` component, so not necessary.

2022-09-07 21:31 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/settings/index.tsx
> +      {/*<View style={[styles.flex1]}></View>*/}
unused code?

2022-09-08 06:13 UTC, BlockJayn commented
Thx for the feedback @inyono, requested changes are done

2022-09-08 11:10 UTC, inyono approved these changes
Thanks :)

2022-09-08 11:10 UTC, merged