Feature/fav icons share reload
obi-wallet/obi-wallet pull request #88
Opened 2022-09-07 20:38 UTC by HERRKIN

2022-09-07 21:23 UTC, inyono requested changes

2022-09-07 21:23 UTC, inyono commented on obi-wallet/apps/mobile/src/app/biometrics/index.ts
> -        Keychain.ACCESS_CONTROL.BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE,
This should be a dev only change (required for simulators on iOS 13 but not on real device) since it decreases security. So either add a check for NODE_ENV === 'production' or remove it from the code base (and manually change it when working with simulators)

2022-09-07 21:23 UTC, inyono commented on obi-wallet/apps/mobile/src/app/biometrics/index.ts
> -      Keychain.ACCESS_CONTROL.BIOMETRY_CURRENT_SET_OR_DEVICE_PASSCODE,
same

2022-09-07 21:23 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/connected-web-view/index.tsx
> -    const webviewRef = useRef<WebView>();
This change breaks things since webViewRef is not defined for the other usages (which `yarn checks` also shows, including that you forgot to run `yarn format` before committing).

So:
- Has to be a `MutableRef`, otherwise you can't access `current`
- Has to be passed in all usages of `ConnectedWebView` or handled in some different way. Cleaner solution would be to use something like forward ref and only expose functionality needed (i.e. refreshing or whatever you want).

2022-09-07 21:23 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/web-view.tsx
> +    const WebViewRef = useRef<WebView>(null);
This should be `webViewRef`.

2022-09-07 21:23 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/web-view.tsx
> +        // />
unused code

2022-09-08 19:47 UTC, HERRKIN commented on obi-wallet/apps/mobile/src/app/screens/components/connected-web-view/index.tsx
> -    const webviewRef = useRef<WebView>();
I had to delete this line but I changed the type Ref to MutableRef

2022-09-08 19:48 UTC, HERRKIN commented on obi-wallet/apps/mobile/src/app/screens/web-view.tsx
> +    const WebViewRef = useRef<WebView>(null);
should be good now

2022-09-08 19:53 UTC, inyono commented on obi-wallet/apps/mobile/src/app/screens/components/connected-web-view/index.tsx
> -    const webviewRef = useRef<WebView>();
Still the same problem, see `yarn checks`...

2022-09-10 22:24 UTC, merged