feature/onboarding buttons & loading-feature
obi-wallet/obi-wallet pull request #99
Opened 2022-09-09 11:56 UTC by BlockJayn

- Added "disable on click" to prevent doubleclick on buttons (Verify..) to the last steps of onboarding process (signature-modal)
- Added conditional enabled button based on minCharsLength for security answer in modal
- Added Loading-Feature after the very last "confirm" Button to provide a smooth waiting experience while transitioning to the main app. 
- incl. "yarn format"

After last "Confirm":
![simulator_screenshot_0B409EF0-B10C-465E-ADF1-6E65AF481E65](https://user-images.githubusercontent.com/99530800/189343726-b00a4569-45a9-426f-9261-b96be102cae0.png)

2022-09-09 20:28 UTC, inyono requested changes

2022-09-09 20:28 UTC, inyono commented on obi-wallet/apps/mobile/src/app/loader/loader.tsx
> +      <View style={styleBox}>
Do we need two `Views`? Especially since the second one has no styles attached.

- `styleBackdrop` should be renamed to `backdropStyle`, and `styleBox` (if needed) to `boxStyle` for consistency. If you only need one of those, you can also name it `style`.
- `Loader` is missing TypeScript types.
-  The style props should be marked as optional.

2022-09-10 08:31 UTC, BlockJayn commented on obi-wallet/apps/mobile/src/app/loader/loader.tsx
> +      <View style={styleBox}>
Thx 4 the review!

- The second <View> (styleBox) was more or less an attempt to make it more dynamic - for example if someone wants to reuse the component and wants to wrap a small box around the loader in addition for example. I removed it, as it is not needed in this case right now.

- Added TypeScript-Types (not sure if "style?: any" is correct. I tried to limit it to CSSProperties or string, but somehow the only thing that works is "any"...)

2022-09-10 20:27 UTC, inyono commented on obi-wallet/apps/mobile/src/app/loader/loader.tsx
> +interface LoaderProps extends React.HTMLAttributes<HTMLAllCollection> {
Why do we extend from React.HTMLAttributes?

2022-09-10 20:28 UTC, inyono commented on obi-wallet/apps/mobile/src/app/loader/loader.tsx
> +  style?: any;
That should be `StyleProp<ViewStyle>` instead of `any`

2022-09-10 20:30 UTC, inyono commented on obi-wallet/apps/mobile/src/app/loader/loader.tsx
> +      <View style={styleBox}>
* Yeah, don't generalize stuff that isn't needed right now. You can do that later when you have an actual use case :)
* Added a comment on how to type `style`. You can find that out yourselves, btw, by checking out the `ViewProps` (e.g. Command-Clicking `View` or `style` which should lead you to the types).

2022-09-10 22:18 UTC, inyono approved these changes

2022-09-10 22:18 UTC, merged